app/app/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('register.urls')),
    path('', include('catalog.urls')),
]

app/catalog/urls.py
from django.contrib import admin
from django.urls import path,include
from catalog import views
app_name = 'catalog'
urlpatterns = [
    path('catalog/', views.catalog,name='catalog'),
    path('product/', views.product,name='product'),
]

app/main/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.index,name='index')
]

app/register/urls.py
from django.contrib import admin
from django.urls import path,include
from register import views
app_name = 'register'
urlpatterns = [
    path('login/', views.login_view,name='login'),
    path('register/', views.register,name='register'),
    path('logout/', views.logout_view,name='logout'),
]

app/catalog/models.py
from django.db import models

# Create your models here.

app/main/models.py
from django.conf import settings
from django.db import models

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

# Create your models here.

app/register/models.py
from django.db import models
# Create your models here.

app/main/forms.py
from django import forms
from .models import Review
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['message']  

        labels = {
            'message': '',
        }

app/catalog/views.py
from django.shortcuts import render

# Create your views here.
def catalog(request):
    context= {
        'title': 'Home',
        'content': 'Главная страница'
    }
    return render(request, 'catalog/catalog.html', context)
def product(request):
    context= {
        'title': 'Home',
        'content': 'Главная страница'
    }
    return render(request, 'catalog/product.html', context)

app/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from .models import Review
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from main import views
from .forms import ReviewForm


# Create your views here.
def index(request):
    context= {
        'title': 'Home',
        'content': 'Главная страница'
    }
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            messages.success(request, "Отзыв отправлен!")
            return redirect('main:index')
    else:
        review_form = ReviewForm()

    return render(request, 'main/index.html', {
        'review_form': review_form
    })

app/register/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from main import views
from main import urls

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, 'Вы успешно вошли в систему!')
            return redirect('main:index')
        else:
            messages.error(request, 'Неверный логин или пароль!')
    return render(request, 'register/login.html')

def register(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        last_name = request.POST.get('name')
        email = request.POST.get('email')
        id = request.POST.get('tel')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
  
        if not username or not last_name or not email or not password or not confirm_password:
            messages.error(request, 'Все поля обязательны для заполнения!')
            return render(request, 'register/register.html')
   
        if password != confirm_password:
            messages.error(request, 'Пароли не совпадают!')
            return render(request, 'register/register.html')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Пользователь с таким логином уже существует.')
            return render(request, 'register/register.html')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'Пользователь с таким email уже существует.')
            return render(request, 'register/register.html')
      
        password_hash = make_password(password)
    
        user = User.objects.create(
            username=username,
            last_name=last_name,
            email=email,
            password=password_hash  
        )
        
        login(request, user)

        return redirect('main:index') 

    return render(request, 'register/register.html') 

def logout_view(request):
    logout(request)
    messages.success(request, 'Вы вышли из системы.')
    return redirect('main:index')

app/catalog/templates/catalog/card.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Вход'}}{% endblock %}

{% block content %}


{% endblock %}

app/catalog/templates/catalog/catalog.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Каталог'}}{% endblock %}

{% block content %}
<section class="sectionFil">
<div class="filters">
    <h2>Отличия</h2>
<ul>
    <li>Размер</li>
    <li>Тип шерсти</li>
    <li>Тип породы/предназначение</li>
    <li>Характер и поведение</li>
    <li>Уровень ухода</li>
    <li>Физическая активность</li>
    <li>Условия содержания</li>
    <li>Социальность</li>
    <li>здоровье</li>
    <li>Интеллект и обучение</li>
</ul>
</div>
<h1 class="unfound">Породы не найдены</h1>
</section>
{% endblock %}

app/main/templates/main/base.html
{% load static%}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
</head>

<body>
    <header>
        <h1>PawPick</h1>
        <!-- <img src="" alt=""> -->

        <nav class="nav">      
            <a href="{% url 'main:index' %}" class="button"> Тест </a>
            <a href="{% url 'catalog:catalog' %}" class="button"> Собаки </a>
            <a href="#" class="button"> Спасатели</a>
            <a href="#" class="button"> Избранное</a>
        </nav> 
        {% if request.user.is_authenticated %}
            <a href="{% url 'register:logout' %}" class="button"> Выход</a>
        {%else%}
        <span class="reg"><a href="{% url "register:login" %}" >Вход</a>|<a href="{% url "register:register" %}">Регистрация</a></span>
        {%endif%}
      

    </header>

<main>
    {% block content %}

    {% endblock %}
    </main>
    <footer>
        <div class="container">
        <div class="footer">
        <div class="footer_sec1">
            <nav class="nav">
            <a href="{% url 'main:index' %}" class="button"> Тест </a>
            <a href="{% url 'catalog:catalog' %}" class="button"> Собаки </a>
            <a href="#" class="button"> Спасатели</a>
            <a href="#" class="button"> Избранное</a>
            </nav>
             <h1>Корочки.есть</h1>
        </div>
        <div class="divider"></div>
        <div class="footer_sec2">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem amet dolore accusamus, nisi illo error voluptates commodi porro unde adipisci, temporibus nihil voluptate consequuntur, natus eum! Accusantium dolorum sunt reiciendis.</p>
            <h2>соц</h2>
        </div>
        </div>
        </div>
    </footer>
    {% load static %}
    <script src="{% static '/main/js/main.js' %}"></script>
</body>

</html>

app/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Главная страница'}}{% endblock %}

{% block content %}
<section class="section1">
    <div class="container">
        <div class="wrapper">
            <div class="section1_banner fade-in">
                <h1>Заголовок</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque omnis, perferendis at facilis, facere
                    accusantium fugit vitae voluptatem odio itaque porro numquam assumenda, aspernatur dignissimos
                    reiciendis pariatur repellendus esse laudantium!</p>
                <a href="" class="btn sec1btn"><span>Пройти ТЕСТ</span></a>
            </div>

            <div class="section1_slider fade-in">
<img src="/static/main/img/slider.svg" alt="">
            </div>
        </div>
    </div>
</section>

<img src="/static/main/img/divider1.svg" alt="" class="divider1">
<section class="section2">
    <div class="container">
        <div class="wrapper">
            <div class="section2_testbtn fade-in">
                <img src="/static/main/img/testbtn.svg" alt="">
            </div>
            <div class="section2_navbtn fade-in">
                <a href="{% url 'catalog:catalog' %}" class="ticket">
                    <div class="navbtn">
                    <h2>Наши Собачки</h2>
                    <div class="mini_divider"></div>
                    <p>Список всех доступных <br>на нашем сайте пород</p>
                    </div>
                </a>
                <a href="" class="ticket">
                    <div class="navbtn navbtn2">
                    <h2>Ветклиники и приюты</h2>
                    <div class="mini_divider"></div>
                    <p>Главные помощники для <br> наших друзей младших</p>
                    </div>
                   
                </a>
            </div>
        </div>
    </div>
</section>

<img src="/static/main/img/divider2.svg" alt="" class="dividers">
<section class="section3">
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Neque corrupti voluptas sit blanditiis consectetur?
        Beatae ipsa esse laborum! Nulla laborum placeat expedita. Eos nemo maiores, voluptatum doloribus dolor quaerat
        magnam.</p>
    <div class="reel">
        <div class="sec3slider">

        <img src="/static/main/img/img1.png" alt="">
        <img src="/static/main/img/img2.png" alt="">
        <img src="/static/main/img/img3.png" alt="">
        </div>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum mollitia quisquam quas, eaque officiis dolores
        nemo quos ad beatae! Quo dolore nostrum exercitationem quam tempore nisi enim possimus eaque eligendi!</p>
</section>


<img src="/static/main/img/divider1.svg" alt="" class="divider1">
<section class="section4">
    <div class="container">
    <div class="wrapper sec4_wrap">
        <div class="sec4_form fade-in">
         <span class="form_title"><h2>Отзыв</h2></span>
        <div class="form">
        
        <form method="POST" class="form_form">
        {% csrf_token %}
        {{ review_form.as_p }}
         <button type="submit" class="btn btn_form" method="POST"><span>Отправить</span></button>
        </form>
    </div>
    </div>
    <div class="section4_info fade-in">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam sed eligendi provident beatae commodi,
            accusamus debitis? Obcaecati iusto laudantium et repellendus soluta. Voluptate vero officiis facilis
            repudiandae, ipsa quaerat molestiae.</p>
    </div>
    </div>
    </div>
</section>
<img src="/static/main/img/divider2.svg" alt="" class="dividers">
{% endblock %}

app/register/templates/register/login.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Вход'}}{% endblock %}

{% block content %}

<section class="back">
<div class="container cont_form fade-in">
     <span class="form_title"><h2>Вход</h2></span>
    <div class="form">
    <form method="POST" class="form_form">
        {% csrf_token %}
        <label class="text">Введите Логин</label>
        <input type="text" name="username" placeholder="Логин..." class="form_input" required>

        <label class="text">Введите Пароль</label>
        <input type="password" name="password" placeholder="Пароль..." class="form_input" required>
 <a href="{% url 'register:register' %}" class="abtn">Нет аккаунта? Зарегистрируйтесь.</a>
        <button type="submit" class="btn btn_form"><span> Войти</span></button>
    </form>
   
    </div>
</div>
</section>
{% endblock %}

app/register/templates/register/register.html
{% extends 'main/base.html' %}
{% load static%}
{% block title %}{{'Регистрация'}}{% endblock %}

{% block content %}

<section class="back">
<div class="container cont_form fade-in">
        <span class="form_title"><h2>Регистрация</h2></span>
    <div class="form">
    <form method="POST" class="form_form">
        {% csrf_token %}
        <label class="text">Введите Логин</label>
        <input type="text" id="username" name="username" placeholder="Логин..." class="form_input" required>

        <label class="text">Введите ФИО</label>
        <input type="text" id="name" name="name" placeholder="ФИО..." class="form_input" required>

        <label class="text">Введите Email</label>
        <input type="email" id="email" name="email" placeholder="Email..." class="form_input" required>

        <label class="text">Введите Пароль</label>
        <input type="password" id="password" name="password" placeholder="Пароль..." class="form_input" required>

        <label class="text">Подтвердите Пароль</label>
        <input type="password" id="confirm_password" name="confirm_password" placeholder="Пароль..." class="form_input"
            required>
        <a href="{% url 'register:login' %} " class="abtn">Есть аккаунт? Войдите.</a>
        <button type="submit" class="btn btn_form"><span> Зарегистрироваться</span></button>
    </form>


    </div>
</div>
</section>
{% endblock %}